name = "example"
type = "javascript"
compatibility_date = "2023-04-11"
main = "build/index.js"

[build]
command = "cargo install -q worker-build && worker-build --release" # required
image_builder = ""
dir = "build"
