apiVersion: apps/v1
kind: Deployment
metadata:
  name: workerd
spec:
  selector:
    matchLabels:
      app: workerd
  replicas: 1
  template:
    metadata:
      labels:
        app: workerd
    spec:
      containers:
        - name: workerd
          image: clementreiffers/artist-worker
          ports:
            - containerPort: 8080
              hostPort: 8080
            - containerPort: 8081
              hostPort: 8081
