apiVersion: v1
kind: Namespace
metadata:
  name: worker
---
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: workerd-hpa
  namespace: worker
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: workerd-depl
  minReplicas: 1
  maxReplicas: 3
  metrics:
    - type: Resource
      resource:
        name: cpu
        target:
          type: Utilization
          averageUtilization: 60
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: workerd-depl
  namespace: worker
  labels:
      app: workerd-depl
spec:
  selector:
    matchLabels:
      app: workerd-depl
  replicas: 1
  template:
    metadata:
      labels:
        app: workerd-depl
    spec:
      containers:
        - name: workerd-depl
          image: clementreiffers/artist-worker
          resources:
            limits:
              cpu: 70m
            requests:
              cpu: 70m
          ports:
            - containerPort: 8080
              hostPort: 8080
            - containerPort: 8081
              hostPort: 8081
---
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: artist-worker
  name: artist-worker
  namespace: worker
spec:
  ports:
    - name: artist-worker
      port: 8080
      protocol: TCP
      targetPort: 8080
  selector:
    app: workerd-depl
  type: NodePort
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: hello-world-worker
  name: hello-world-worker
  namespace: worker
spec:
  ports:
    - name: hello-world-worker
      port: 8081
      protocol: TCP
      targetPort: 8081
  selector:
    app: workerd-depl
  type: NodePort
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: artist-worker
  namespace: worker
  labels:
    app: artist-worker
spec:
  rules:
    - host: ba113b6b-0746-4372-b61c-8c8897262f13.pub.instances.scw.cloud
      http:
        paths:
          - path: /artist
            pathType: Prefix
            backend:
              service:
                name: artist-worker
                port:
                  number: 8080
          - path: /hello-world
            pathType: Prefix
            backend:
              service:
                name: hello-world-worker
                port:
                  number: 8081
---
