apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: workerd-hpa
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: workerd-depl
  minReplicas: 1
  maxReplicas: 3
  metrics:
    - type: Resource
      resource:
        name: cpu
        target:
          type: Utilization
          averageUtilization: 60
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: workerd-depl
  labels:
      app: workerd-depl
spec:
  selector:
    matchLabels:
      app: workerd-depl
  replicas: 1
  template:
    metadata:
      labels:
        app: workerd-depl
    spec:
      containers:
        - name: workerd-depl
          image: clementreiffers/artist-worker
          resources:
            limits:
              cpu: 70m
            requests:
              cpu: 70m
          ports:
            - containerPort: 8080
              hostPort: 8080
            - containerPort: 8081
              hostPort: 8081
