apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: artist-worker
  labels:
    app: artist-worker
spec:
  rules:
  - http:
      paths:
        - path: /artist
          pathType: Prefix
          backend:
            service:
              name: artist-worker
              port:
                number: 8080
        - path: /hello-world
          pathType: Prefix
          backend:
            service:
              name: hello-world-worker
              port:
                number: 8081
